enable:
  issues: true
  prs: true

labels:
  'Bug':
    include:
    - '[BUG]'
    - 'bug'
  'Feature':
    include:
    - '[FEAT]'
    - 'feat'
  'Documentation':
    include:
      - '[DOCS]'
      - 'docs'
  'Style':
    include:
      - '[STYLE]'
      - 'style'
  'Refactoring':
    include:
      - '[REFACTOR]'
      - 'refactor'
  'Test':
    include:
      - '[TEST]'
      - 'test'
  'Chore':
    include:
      - '[CHORE]'
      - 'chore'

