server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: DoItTogether

  data:
    redis:
      host: ${REDIS_HOST} # redis 서버의 호스트 이름
      port: ${REDIS_PORT} # redis 서버의 포트 번호
      maxmemory: 128M
      invite-link:
        url: ${REDIS_INVITE_URL}
        ttl-minutes: ${REDIS_INVITE_TTL} # 초대 링크 TTL (분)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${HOME_URL}
    username: ${HOME_USERNAME}
    password: ${HOME_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  #    hibernate:
  #      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_RESTAPI_KEY}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao_url:
  valid-uri: https://kapi.kakao.com/v1/user/access_token_info
  logout-uri: https://kapi.kakao.com/v1/user/logout

springdoc:
  api-docs:
    path: /api-docs  # API 문서의 기본 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI에 접근하기 위한 URL 경로
    operationsSorter: alpha  # API 정렬 기준 (alpha: 알파벳순)
    tagsSorter: alpha        # 태그 정렬 기준
    disable-swagger-default-url: true # Swagger 기본 URL 표시 비활성화
