spring:
  config:
    activate:
      on-profile: test

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER,VALUE
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect