server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: DoItTogether

  data:
    redis:
      host: localhost # redis 서버의 호스트 이름
      port: 6379 # redis 서버의 포트 번호
      maxmemory: 128M

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${HOME_URL}
    username: ${HOME_USERNAME}
    password: ${HOME_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
            format_sql: true
    database: mysql
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /api-docs  # API 문서의 기본 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI에 접근하기 위한 URL 경로
    operationsSorter: alpha  # API 정렬 기준 (alpha: 알파벳순)
    tagsSorter: alpha        # 태그 정렬 기준
    disable-swagger-default-url: true # Swagger 기본 URL 표시 비활성화

